db:
  mysql:
    host: 127.0.0.1
    user: root
    pass: 123123
    name: test
    port: 3306
    charset: utf8
    collation: utf8_unicode_ci
    prefix:
cache:
  redis:
    host: 127.0.0.1
    port: 6379
queue:
  rabbit:
    host: 127.0.0.1
    port: 5672
    login: demo
    password: 123123
    vhost: demo
